add nav stlying
KartheekWD/newsweek-clone pull request #2
Opened 2020-08-18 10:28 UTC by RICKCOYL

2020-08-22 13:47 UTC, SafaErden requested changes
## Status: Require changes ♻️ 🚥 

Hi **TEAM**, your project is awesome and it really looks exactly like the original. 👐 However, we need a little fix before we can proceed. Kindly find comments below:

<hr>

- [x] Your page has a horizontal scroll depending on the different screen sizes. Please fix it.

![image](https://user-images.githubusercontent.com/60184961/90957042-1a8d9300-e494-11ea-8c60-d35590e25ad4.png)

- [ ] `Featured slideshows` section ([link to page](https://www.newsweek.com/)) is missing. Please add that section:

![image](https://user-images.githubusercontent.com/60184961/90957179-eebedd00-e494-11ea-99a7-98738a3787b0.png)

- [ ] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
* no repeating of the same rule, so please consider following the DRY CSS rules.

<hr>

**_NOTE_**

* Your PR should have a meaningful title and a brief description. The title of your PR is missing in this project. Please do not disregard writing titles for your upcoming projects' PRs. Do not forget that poor PR is an invalidation reason.

* Some of the commit messages contain typos. Please be careful about that issue in your upcoming projects.

* Even the requirement checklist tells that the students should create the 'latest news' section, I noticed that the original page does not contain that section on the date that you created the project. So this item is disregarded by me while reviewing your code.

<hr>

As I mentioned above, your project is almost done. You have some minor issues to solve. Please be an optimist and do not forget that the main purpose is to learn and practice. Do not let the requested changes discourage you 👍

<hr>

Kindly make the changes (also check the ones attached below) and submit another code review
Happy coding_ 👨‍💻 

**Safa ERDEN**

2020-08-22 13:47 UTC, SafaErden commented on README.md
> +This project is [MIT](lic.url) licensed.
- [x] The MIT license link is broken, please fix it.

2020-08-22 13:47 UTC, SafaErden commented on index.html
> +    </header>
- [ ] Please apply the proper bootstrap classes to make your header fixed as it is in the original page.

2020-08-22 13:47 UTC, SafaErden commented on index.html
> +
- [OPTIONAL] Consider the use of the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document

2020-08-22 13:47 UTC, SafaErden commented on index.html
> +              <input class="news-letter-input btn-sm border-1" type="text" placeholder="Email Address" />
- [x] Please apply the proper Bootstrap classes to the input field to create the same UI with the original page.

![image](https://user-images.githubusercontent.com/60184961/90957297-4f4e1a00-e495-11ea-9158-b367ae71614b.png)

2020-08-22 13:47 UTC, SafaErden commented on index.html
> +          <h4 class="font-weight-bold py-sm-3 ml-sm-2">NEWS LETTER</h4>
- [ ] Please fix the typo (newsletter instead of news letter).

2020-08-22 13:47 UTC, SafaErden commented on index.html
> +
* [OPTIONAL] You can use proper code-formatters to prevent redundant empty lines and improper indentations.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +}
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +  color: white;
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +}
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +  color: #000;
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +  bottom: 0;
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +  background-color: #000;
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +}
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +  display: inline-block;
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +  display: inline-block;
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +  }
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +  }
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +    width: 100%;
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +  }
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +  }
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +  }
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +  }
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +    width: 100%;
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +  }
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +    width: 100%;
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +    width: 100%;
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-22 13:47 UTC, SafaErden commented on style.css
> +  }
You should use Bootstrap classes everywhere for styling, so please replace all the custom CSS rule which you can implement with Bootstrap.

2020-08-24 17:44 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

#### You did a very good job on this project, and also refactoring your code after the remarks of the previous TSE :100: 

However, there is one thing that you did not changes: 

- [ ] The navbar needs to have a position fixed.

I marked two details that I think you could change in order to make this project even better, but since this was not required previously they are optional. You can see one here and another in the inline comments below.

- optional: The order of the articles in the mobile version is different in the original from what is on your clone. Would be a great practice to let equal to the original using the display none classes.

#### As stated above, the project looks really good.

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:

2020-08-24 17:44 UTC, expjazz commented on index.html
> +          <img class="newsweek-logo ml-3" src="images/newsweek-logo.svg" alt="NewsWeek-logo" />
- [ ] The header is still not fixed.

| Yours | Original |
|:---:|:---:|
![image](https://user-images.githubusercontent.com/61479648/91076511-040f4500-e616-11ea-93ae-183f2dbbcde4.png) | ![image](https://user-images.githubusercontent.com/61479648/91076729-4afd3a80-e616-11ea-8d43-00b1c6c07912.png) |

2020-08-24 17:44 UTC, expjazz commented on index.html
> +              <div class="mb-4 mt-4 d-flex">
- optional: The text should wrap around the image in all screen sizes

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/91077439-72083c00-e617-11ea-925e-e97e627effce.png) |![image](https://user-images.githubusercontent.com/61479648/91077477-7e8c9480-e617-11ea-8c29-1143328f22d3.png)  |

2020-08-25 17:02 UTC, tirthajyoti-ghosh approved these changes
# Approved ✅

## You have done an incredible job making this project 👏🧨💪! Just perfect 💯! 

### You have met all the requirements of the project. Go ahead and merge it! Onto the next project 🚀 !

Happy coding 👨‍💻 

<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-08-25 17:05 UTC, merged